import { Injectable, signal, computed, inject } from '@angular/core';
import {
  Equipment,
  EquipmentType,
  EquipmentCategory,
  EquipmentStatus,
  EquipmentCondition,
  RiskLevel,
  InventoryItem,
  InventoryCategory,
  InventoryType,
  StockStatus,
  MaintenanceRecord,
  MaintenanceType,
  MaintenanceStatus,
  WorkOrder,
  WorkOrderType,
  WorkOrderPriority,
  WorkOrderStatus,
  Vendor,
  VendorCategory,
  Alert,
  AlertType,
  AlertSeverity,
  DashboardStats,
  AuditLog,
  AuditAction,
  AuditResourceType
} from '@shared/models';

@Injectable({
  providedIn: 'root'
})
export class MockDataService {

  // Current tenant ID for filtering - set by TenantService
  private currentTenantId = signal<string>('tenant-1');

  // Equipment Data
  private readonly _equipment = signal<Equipment[]>(this.generateEquipmentData());
  readonly equipment = computed(() =>
    this._equipment().filter(e => e.tenantId === this.currentTenantId())
  );

  // Inventory Data
  private readonly _inventory = signal<InventoryItem[]>(this.generateInventoryData());
  readonly inventory = computed(() =>
    this._inventory().filter(i => i.tenantId === this.currentTenantId())
  );

  // Maintenance Records
  private readonly _maintenanceRecords = signal<MaintenanceRecord[]>(this.generateMaintenanceData());
  readonly maintenanceRecords = computed(() =>
    this._maintenanceRecords().filter(m => m.tenantId === this.currentTenantId())
  );

  // Work Orders
  private readonly _workOrders = signal<WorkOrder[]>(this.generateWorkOrderData());
  readonly workOrders = computed(() =>
    this._workOrders().filter(w => w.tenantId === this.currentTenantId())
  );

  // Vendors
  private readonly _vendors = signal<Vendor[]>(this.generateVendorData());
  readonly vendors = computed(() =>
    this._vendors().filter(v => v.tenantId === this.currentTenantId())
  );

  // Alerts
  private readonly _alerts = signal<Alert[]>(this.generateAlertData());
  readonly alerts = computed(() =>
    this._alerts().filter(a => a.tenantId === this.currentTenantId())
  );

  // Audit Logs
  private readonly _auditLogs = signal<AuditLog[]>(this.generateAuditLogData());
  readonly auditLogs = this._auditLogs.asReadonly();

  // Set the current tenant for data filtering
  setCurrentTenant(tenantId: string): void {
    this.currentTenantId.set(tenantId);
  }

  getCurrentTenantId(): string {
    return this.currentTenantId();
  }
  
  // Dashboard Stats - filtered by current tenant
  readonly dashboardStats = computed<DashboardStats>(() => {
    const tenantId = this.currentTenantId();
    const equipment = this._equipment().filter(e => e.tenantId === tenantId);
    const inventory = this._inventory().filter(i => i.tenantId === tenantId);
    const workOrders = this._workOrders().filter(w => w.tenantId === tenantId);
    const maintenanceRecords = this._maintenanceRecords().filter(m => m.tenantId === tenantId);
    const alerts = this._alerts().filter(a => a.tenantId === tenantId);

    // Calculate monthly maintenance cost based on tenant
    const maintenanceCostByTenant: Record<string, number> = {
      'tenant-1': 45750,
      'tenant-2': 38500,
      'tenant-4': 125000
    };

    return {
      totalEquipment: equipment.length,
      activeEquipment: equipment.filter(e => e.status === EquipmentStatus.IN_SERVICE).length,
      underMaintenance: equipment.filter(e => e.status === EquipmentStatus.UNDER_MAINTENANCE).length,
      outOfService: equipment.filter(e => e.status === EquipmentStatus.OUT_OF_SERVICE).length,
      totalInventoryItems: inventory.length,
      lowStockItems: inventory.filter(i => i.status === StockStatus.LOW_STOCK || i.status === StockStatus.OUT_OF_STOCK).length,
      pendingWorkOrders: workOrders.filter(w => w.status === WorkOrderStatus.OPEN || w.status === WorkOrderStatus.IN_PROGRESS).length,
      overdueMaintenances: maintenanceRecords.filter(m => m.status === MaintenanceStatus.OVERDUE).length,
      alertsCount: alerts.filter(a => !a.isRead).length,
      monthlyMaintenanceCost: maintenanceCostByTenant[tenantId] || 50000
    };
  });
  
  private generateEquipmentData(): Equipment[] {
    return [
      {
        id: 'EQ001',
        tenantId: 'tenant-1',
        inventoryNumber: 'MED-2024-001',
        name: 'Portable X-Ray System',
        type: EquipmentType.IMAGING,
        category: EquipmentCategory.MONITORING_SURGICAL_ICU,
        manufacturer: 'GE Healthcare',
        model: 'Optima XR220amx',
        serialNumber: 'XR220-2024-A1234',
        location: { id: 'L1', building: 'Main Hospital', floor: '2', room: 'Radiology Suite A' },
        department: 'Radiology',
        status: EquipmentStatus.IN_SERVICE,
        condition: EquipmentCondition.EXCELLENT,
        riskLevel: RiskLevel.HIGH,
        purchaseDate: new Date('2023-06-15'),
        installationDate: new Date('2023-07-01'),
        warrantyExpiry: new Date('2026-06-15'),
        lastMaintenanceDate: new Date('2024-12-01'),
        nextMaintenanceDate: new Date('2025-03-01'),
        purchaseCost: 175000,
        currentValue: 150000,
        powerRequirements: '220V, 30A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        createdAt: new Date('2023-06-15'),
        updatedAt: new Date('2024-12-01')
      },
      {
        id: 'EQ002',
        tenantId: 'tenant-1',
        inventoryNumber: 'MED-2024-002',
        name: 'Patient Monitor - ICU',
        type: EquipmentType.MONITORING,
        category: EquipmentCategory.MONITORING_SURGICAL_ICU,
        manufacturer: 'Philips Healthcare',
        model: 'IntelliVue MX800',
        serialNumber: 'MX800-2024-B5678',
        location: { id: 'L2', building: 'Main Hospital', floor: '3', room: 'ICU Bay 1' },
        department: 'Intensive Care',
        status: EquipmentStatus.IN_SERVICE,
        condition: EquipmentCondition.GOOD,
        riskLevel: RiskLevel.HIGH,
        purchaseDate: new Date('2023-08-20'),
        installationDate: new Date('2023-08-25'),
        warrantyExpiry: new Date('2025-08-20'),
        lastMaintenanceDate: new Date('2024-11-15'),
        nextMaintenanceDate: new Date('2025-02-15'),
        purchaseCost: 45000,
        currentValue: 38000,
        powerRequirements: '110V, 10A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        createdAt: new Date('2023-08-20'),
        updatedAt: new Date('2024-11-15')
      },
      {
        id: 'EQ003',
        tenantId: 'tenant-1',
        inventoryNumber: 'MED-2024-003',
        name: 'Ventilator',
        type: EquipmentType.LIFE_SUPPORT,
        category: EquipmentCategory.LIFE_SUPPORT,
        manufacturer: 'Dräger',
        model: 'Evita V300',
        serialNumber: 'V300-2024-C9012',
        location: { id: 'L3', building: 'Main Hospital', floor: '3', room: 'ICU Bay 2' },
        department: 'Intensive Care',
        status: EquipmentStatus.UNDER_MAINTENANCE,
        condition: EquipmentCondition.FAIR,
        riskLevel: RiskLevel.HIGH,
        purchaseDate: new Date('2022-03-10'),
        installationDate: new Date('2022-03-15'),
        warrantyExpiry: new Date('2024-03-10'),
        lastMaintenanceDate: new Date('2025-01-10'),
        nextMaintenanceDate: new Date('2025-04-10'),
        purchaseCost: 65000,
        currentValue: 45000,
        powerRequirements: '220V, 15A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        createdAt: new Date('2022-03-10'),
        updatedAt: new Date('2025-01-10')
      },
      {
        id: 'EQ004',
        tenantId: 'tenant-1',
        inventoryNumber: 'MED-2024-004',
        name: 'Defibrillator',
        type: EquipmentType.THERAPEUTIC,
        category: EquipmentCategory.SURGICAL_ICU,
        manufacturer: 'Zoll Medical',
        model: 'R Series Plus',
        serialNumber: 'RS-2024-D3456',
        location: { id: 'L4', building: 'Main Hospital', floor: '2', room: 'Emergency Dept' },
        department: 'Emergency',
        status: EquipmentStatus.IN_SERVICE,
        condition: EquipmentCondition.EXCELLENT,
        riskLevel: RiskLevel.HIGH,
        purchaseDate: new Date('2024-01-05'),
        installationDate: new Date('2024-01-08'),
        warrantyExpiry: new Date('2027-01-05'),
        lastMaintenanceDate: new Date('2024-10-01'),
        nextMaintenanceDate: new Date('2025-01-01'),
        purchaseCost: 32000,
        currentValue: 30000,
        powerRequirements: 'Battery/110V',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        createdAt: new Date('2024-01-05'),
        updatedAt: new Date('2024-10-01')
      },
      {
        id: 'EQ005',
        tenantId: 'tenant-1',
        inventoryNumber: 'MED-2024-005',
        name: 'Ultrasound System',
        type: EquipmentType.DIAGNOSTIC,
        category: EquipmentCategory.MONITORING_PHYSIOLOGICAL,
        manufacturer: 'Siemens Healthineers',
        model: 'ACUSON Sequoia',
        serialNumber: 'SEQ-2024-E7890',
        location: { id: 'L5', building: 'Main Hospital', floor: '1', room: 'Imaging Suite B' },
        department: 'Radiology',
        status: EquipmentStatus.IN_SERVICE,
        condition: EquipmentCondition.GOOD,
        riskLevel: RiskLevel.MEDIUM,
        purchaseDate: new Date('2023-11-20'),
        installationDate: new Date('2023-12-01'),
        warrantyExpiry: new Date('2026-11-20'),
        lastMaintenanceDate: new Date('2024-09-15'),
        nextMaintenanceDate: new Date('2025-03-15'),
        purchaseCost: 125000,
        currentValue: 110000,
        powerRequirements: '110V, 15A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        createdAt: new Date('2023-11-20'),
        updatedAt: new Date('2024-09-15')
      },
      {
        id: 'EQ006',
        tenantId: 'tenant-1',
        inventoryNumber: 'MED-2024-006',
        name: 'Infusion Pump',
        type: EquipmentType.THERAPEUTIC,
        category: EquipmentCategory.SURGICAL_ICU,
        manufacturer: 'B. Braun',
        model: 'Infusomat Space',
        serialNumber: 'IS-2024-F1234',
        location: { id: 'L6', building: 'Main Hospital', floor: '4', room: 'Medical Ward A' },
        department: 'Medical',
        status: EquipmentStatus.IN_SERVICE,
        condition: EquipmentCondition.GOOD,
        riskLevel: RiskLevel.HIGH,
        purchaseDate: new Date('2024-02-15'),
        installationDate: new Date('2024-02-18'),
        warrantyExpiry: new Date('2026-02-15'),
        lastMaintenanceDate: new Date('2024-11-01'),
        nextMaintenanceDate: new Date('2025-02-01'),
        purchaseCost: 8500,
        currentValue: 7800,
        powerRequirements: 'Battery/110V',
        operatingManualAvailable: true,
        serviceManualAvailable: false,
        createdAt: new Date('2024-02-15'),
        updatedAt: new Date('2024-11-01')
      },
      {
        id: 'EQ007',
        tenantId: 'tenant-1',
        inventoryNumber: 'MED-2024-007',
        name: 'Anesthesia Machine',
        type: EquipmentType.LIFE_SUPPORT,
        category: EquipmentCategory.LIFE_SUPPORT,
        manufacturer: 'GE Healthcare',
        model: 'Aisys CS2',
        serialNumber: 'ACS2-2024-G5678',
        location: { id: 'L7', building: 'Main Hospital', floor: '2', room: 'OR Suite 1' },
        department: 'Surgery',
        status: EquipmentStatus.IN_SERVICE,
        condition: EquipmentCondition.EXCELLENT,
        riskLevel: RiskLevel.HIGH,
        purchaseDate: new Date('2023-09-01'),
        installationDate: new Date('2023-09-10'),
        warrantyExpiry: new Date('2026-09-01'),
        lastMaintenanceDate: new Date('2024-12-15'),
        nextMaintenanceDate: new Date('2025-03-15'),
        purchaseCost: 95000,
        currentValue: 85000,
        powerRequirements: '220V, 20A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        createdAt: new Date('2023-09-01'),
        updatedAt: new Date('2024-12-15')
      },
      {
        id: 'EQ008',
        tenantId: 'tenant-1',
        inventoryNumber: 'MED-2024-008',
        name: 'ECG Machine',
        type: EquipmentType.DIAGNOSTIC,
        category: EquipmentCategory.MONITORING_PHYSIOLOGICAL,
        manufacturer: 'Nihon Kohden',
        model: 'ECG-2550',
        serialNumber: 'ECG-2024-H9012',
        location: { id: 'L8', building: 'Main Hospital', floor: '1', room: 'Cardiology Dept' },
        department: 'Cardiology',
        status: EquipmentStatus.OUT_OF_SERVICE,
        condition: EquipmentCondition.POOR,
        riskLevel: RiskLevel.MEDIUM,
        purchaseDate: new Date('2021-05-20'),
        installationDate: new Date('2021-05-25'),
        warrantyExpiry: new Date('2023-05-20'),
        lastMaintenanceDate: new Date('2024-08-01'),
        nextMaintenanceDate: new Date('2024-11-01'),
        purchaseCost: 12000,
        currentValue: 4000,
        powerRequirements: '110V, 5A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        notes: 'Awaiting replacement - display malfunction',
        createdAt: new Date('2021-05-20'),
        updatedAt: new Date('2024-08-01')
      },
      {
        id: 'EQ009',
        tenantId: 'tenant-1',
        inventoryNumber: 'MED-2024-009',
        name: 'Laboratory Centrifuge',
        type: EquipmentType.LABORATORY,
        category: EquipmentCategory.LABORATORY_ANALYTICAL,
        manufacturer: 'Eppendorf',
        model: '5810R',
        serialNumber: 'EP5810-2024-I3456',
        location: { id: 'L9', building: 'Laboratory Building', floor: '1', room: 'Lab Room 101' },
        department: 'Laboratory',
        status: EquipmentStatus.IN_SERVICE,
        condition: EquipmentCondition.GOOD,
        riskLevel: RiskLevel.LOW,
        purchaseDate: new Date('2023-04-10'),
        installationDate: new Date('2023-04-15'),
        warrantyExpiry: new Date('2025-04-10'),
        lastMaintenanceDate: new Date('2024-10-10'),
        nextMaintenanceDate: new Date('2025-04-10'),
        purchaseCost: 18000,
        currentValue: 15000,
        powerRequirements: '220V, 10A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        createdAt: new Date('2023-04-10'),
        updatedAt: new Date('2024-10-10')
      },
      {
        id: 'EQ010',
        tenantId: 'tenant-1',
        inventoryNumber: 'MED-2024-010',
        name: 'Autoclave',
        type: EquipmentType.STERILIZATION,
        category: EquipmentCategory.OTHER,
        manufacturer: 'Tuttnauer',
        model: '3870EA',
        serialNumber: 'TT3870-2024-J7890',
        location: { id: 'L10', building: 'Main Hospital', floor: '0', room: 'CSSD' },
        department: 'Central Sterile',
        status: EquipmentStatus.IN_SERVICE,
        condition: EquipmentCondition.GOOD,
        riskLevel: RiskLevel.MEDIUM,
        purchaseDate: new Date('2022-08-15'),
        installationDate: new Date('2022-08-25'),
        warrantyExpiry: new Date('2024-08-15'),
        lastMaintenanceDate: new Date('2024-11-20'),
        nextMaintenanceDate: new Date('2025-02-20'),
        purchaseCost: 28000,
        currentValue: 22000,
        powerRequirements: '220V, 30A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        createdAt: new Date('2022-08-15'),
        updatedAt: new Date('2024-11-20')
      },
      // ============ Sunrise Medical Center (tenant-2) Equipment ============
      {
        id: 'EQ-SMC-001',
        tenantId: 'tenant-2',
        inventoryNumber: 'SMC-2024-001',
        name: 'CT Scanner',
        type: EquipmentType.IMAGING,
        category: EquipmentCategory.MONITORING_SURGICAL_ICU,
        manufacturer: 'Siemens Healthineers',
        model: 'SOMATOM go.Top',
        serialNumber: 'CT-SMC-2024-A001',
        location: { id: 'SMC-L1', building: 'Main Building', floor: '1', room: 'CT Suite' },
        department: 'Radiology',
        status: EquipmentStatus.IN_SERVICE,
        condition: EquipmentCondition.EXCELLENT,
        riskLevel: RiskLevel.HIGH,
        purchaseDate: new Date('2024-01-15'),
        installationDate: new Date('2024-02-01'),
        warrantyExpiry: new Date('2027-01-15'),
        lastMaintenanceDate: new Date('2024-11-15'),
        nextMaintenanceDate: new Date('2025-02-15'),
        purchaseCost: 850000,
        currentValue: 810000,
        powerRequirements: '480V, 100A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        createdAt: new Date('2024-01-15'),
        updatedAt: new Date('2024-11-15')
      },
      {
        id: 'EQ-SMC-002',
        tenantId: 'tenant-2',
        inventoryNumber: 'SMC-2024-002',
        name: 'Digital Mammography System',
        type: EquipmentType.IMAGING,
        category: EquipmentCategory.MONITORING_PHYSIOLOGICAL,
        manufacturer: 'Hologic',
        model: 'Selenia Dimensions',
        serialNumber: 'MAM-SMC-2024-B002',
        location: { id: 'SMC-L2', building: 'Women\'s Center', floor: '2', room: 'Imaging Suite 1' },
        department: 'Radiology',
        status: EquipmentStatus.IN_SERVICE,
        condition: EquipmentCondition.GOOD,
        riskLevel: RiskLevel.MEDIUM,
        purchaseDate: new Date('2023-05-20'),
        installationDate: new Date('2023-06-01'),
        warrantyExpiry: new Date('2026-05-20'),
        lastMaintenanceDate: new Date('2024-12-01'),
        nextMaintenanceDate: new Date('2025-03-01'),
        purchaseCost: 320000,
        currentValue: 280000,
        powerRequirements: '220V, 30A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        createdAt: new Date('2023-05-20'),
        updatedAt: new Date('2024-12-01')
      },
      {
        id: 'EQ-SMC-003',
        tenantId: 'tenant-2',
        inventoryNumber: 'SMC-2024-003',
        name: 'Cardiac Catheterization Lab',
        type: EquipmentType.THERAPEUTIC,
        category: EquipmentCategory.SURGICAL_ICU,
        manufacturer: 'Philips Healthcare',
        model: 'Azurion 7 C20',
        serialNumber: 'CATH-SMC-2024-C003',
        location: { id: 'SMC-L3', building: 'Heart Center', floor: '3', room: 'Cath Lab 1' },
        department: 'Cardiology',
        status: EquipmentStatus.IN_SERVICE,
        condition: EquipmentCondition.EXCELLENT,
        riskLevel: RiskLevel.HIGH,
        purchaseDate: new Date('2023-09-01'),
        installationDate: new Date('2023-10-01'),
        warrantyExpiry: new Date('2026-09-01'),
        lastMaintenanceDate: new Date('2024-10-15'),
        nextMaintenanceDate: new Date('2025-01-15'),
        purchaseCost: 1200000,
        currentValue: 1100000,
        powerRequirements: '480V, 150A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        createdAt: new Date('2023-09-01'),
        updatedAt: new Date('2024-10-15')
      },
      {
        id: 'EQ-SMC-004',
        tenantId: 'tenant-2',
        inventoryNumber: 'SMC-2024-004',
        name: 'Dialysis Machine',
        type: EquipmentType.THERAPEUTIC,
        category: EquipmentCategory.LIFE_SUPPORT,
        manufacturer: 'Fresenius',
        model: '5008S CorDiax',
        serialNumber: 'DIA-SMC-2024-D004',
        location: { id: 'SMC-L4', building: 'Main Building', floor: '2', room: 'Dialysis Unit' },
        department: 'Nephrology',
        status: EquipmentStatus.UNDER_MAINTENANCE,
        condition: EquipmentCondition.FAIR,
        riskLevel: RiskLevel.HIGH,
        purchaseDate: new Date('2022-03-15'),
        installationDate: new Date('2022-04-01'),
        warrantyExpiry: new Date('2024-03-15'),
        lastMaintenanceDate: new Date('2025-01-20'),
        nextMaintenanceDate: new Date('2025-04-20'),
        purchaseCost: 45000,
        currentValue: 32000,
        powerRequirements: '220V, 20A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        notes: 'Undergoing pump replacement',
        createdAt: new Date('2022-03-15'),
        updatedAt: new Date('2025-01-20')
      },
      {
        id: 'EQ-SMC-005',
        tenantId: 'tenant-2',
        inventoryNumber: 'SMC-2024-005',
        name: 'Surgical Microscope',
        type: EquipmentType.DIAGNOSTIC,
        category: EquipmentCategory.SURGICAL_ICU,
        manufacturer: 'Zeiss',
        model: 'OPMI Pentero 900',
        serialNumber: 'MIC-SMC-2024-E005',
        location: { id: 'SMC-L5', building: 'Surgery Center', floor: '3', room: 'OR Suite 2' },
        department: 'Surgery',
        status: EquipmentStatus.IN_SERVICE,
        condition: EquipmentCondition.GOOD,
        riskLevel: RiskLevel.MEDIUM,
        purchaseDate: new Date('2023-07-01'),
        installationDate: new Date('2023-07-15'),
        warrantyExpiry: new Date('2026-07-01'),
        lastMaintenanceDate: new Date('2024-09-01'),
        nextMaintenanceDate: new Date('2025-03-01'),
        purchaseCost: 425000,
        currentValue: 380000,
        powerRequirements: '220V, 15A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        createdAt: new Date('2023-07-01'),
        updatedAt: new Date('2024-09-01')
      },
      {
        id: 'EQ-SMC-006',
        tenantId: 'tenant-2',
        inventoryNumber: 'SMC-2024-006',
        name: 'Blood Gas Analyzer',
        type: EquipmentType.LABORATORY,
        category: EquipmentCategory.LABORATORY_ANALYTICAL,
        manufacturer: 'Radiometer',
        model: 'ABL90 FLEX PLUS',
        serialNumber: 'BGA-SMC-2024-F006',
        location: { id: 'SMC-L6', building: 'Main Building', floor: '1', room: 'Lab Room 102' },
        department: 'Laboratory',
        status: EquipmentStatus.IN_SERVICE,
        condition: EquipmentCondition.EXCELLENT,
        riskLevel: RiskLevel.LOW,
        purchaseDate: new Date('2024-04-01'),
        installationDate: new Date('2024-04-10'),
        warrantyExpiry: new Date('2027-04-01'),
        lastMaintenanceDate: new Date('2024-12-15'),
        nextMaintenanceDate: new Date('2025-03-15'),
        purchaseCost: 38000,
        currentValue: 36000,
        powerRequirements: '110V, 10A',
        operatingManualAvailable: true,
        serviceManualAvailable: false,
        createdAt: new Date('2024-04-01'),
        updatedAt: new Date('2024-12-15')
      },
      // ============ Riverside Community Hospital (tenant-4) Equipment ============
      {
        id: 'EQ-RCH-001',
        tenantId: 'tenant-4',
        inventoryNumber: 'RCH-2024-001',
        name: 'MRI Scanner 3T',
        type: EquipmentType.IMAGING,
        category: EquipmentCategory.MONITORING_SURGICAL_ICU,
        manufacturer: 'GE Healthcare',
        model: 'SIGNA Premier',
        serialNumber: 'MRI-RCH-2024-A001',
        location: { id: 'RCH-L1', building: 'Imaging Center', floor: '1', room: 'MRI Suite A' },
        department: 'Radiology',
        status: EquipmentStatus.IN_SERVICE,
        condition: EquipmentCondition.EXCELLENT,
        riskLevel: RiskLevel.HIGH,
        purchaseDate: new Date('2023-03-01'),
        installationDate: new Date('2023-04-15'),
        warrantyExpiry: new Date('2028-03-01'),
        lastMaintenanceDate: new Date('2024-12-01'),
        nextMaintenanceDate: new Date('2025-03-01'),
        purchaseCost: 2500000,
        currentValue: 2300000,
        powerRequirements: '480V, 200A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        createdAt: new Date('2023-03-01'),
        updatedAt: new Date('2024-12-01')
      },
      {
        id: 'EQ-RCH-002',
        tenantId: 'tenant-4',
        inventoryNumber: 'RCH-2024-002',
        name: 'Linear Accelerator',
        type: EquipmentType.THERAPEUTIC,
        category: EquipmentCategory.SURGICAL_ICU,
        manufacturer: 'Varian',
        model: 'TrueBeam',
        serialNumber: 'LINAC-RCH-2024-B002',
        location: { id: 'RCH-L2', building: 'Cancer Center', floor: '-1', room: 'Radiation Vault 1' },
        department: 'Oncology',
        status: EquipmentStatus.IN_SERVICE,
        condition: EquipmentCondition.EXCELLENT,
        riskLevel: RiskLevel.HIGH,
        purchaseDate: new Date('2022-08-01'),
        installationDate: new Date('2022-10-01'),
        warrantyExpiry: new Date('2027-08-01'),
        lastMaintenanceDate: new Date('2024-11-01'),
        nextMaintenanceDate: new Date('2025-02-01'),
        purchaseCost: 4500000,
        currentValue: 4000000,
        powerRequirements: '480V, 300A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        createdAt: new Date('2022-08-01'),
        updatedAt: new Date('2024-11-01')
      },
      {
        id: 'EQ-RCH-003',
        tenantId: 'tenant-4',
        inventoryNumber: 'RCH-2024-003',
        name: 'Da Vinci Surgical Robot',
        type: EquipmentType.THERAPEUTIC,
        category: EquipmentCategory.SURGICAL_ICU,
        manufacturer: 'Intuitive Surgical',
        model: 'da Vinci Xi',
        serialNumber: 'ROBOT-RCH-2024-C003',
        location: { id: 'RCH-L3', building: 'Surgery Center', floor: '2', room: 'Robotic OR 1' },
        department: 'Surgery',
        status: EquipmentStatus.IN_SERVICE,
        condition: EquipmentCondition.EXCELLENT,
        riskLevel: RiskLevel.HIGH,
        purchaseDate: new Date('2023-06-01'),
        installationDate: new Date('2023-07-15'),
        warrantyExpiry: new Date('2028-06-01'),
        lastMaintenanceDate: new Date('2024-12-15'),
        nextMaintenanceDate: new Date('2025-03-15'),
        purchaseCost: 2800000,
        currentValue: 2600000,
        powerRequirements: '220V, 50A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        createdAt: new Date('2023-06-01'),
        updatedAt: new Date('2024-12-15')
      },
      {
        id: 'EQ-RCH-004',
        tenantId: 'tenant-4',
        inventoryNumber: 'RCH-2024-004',
        name: 'ECMO System',
        type: EquipmentType.LIFE_SUPPORT,
        category: EquipmentCategory.LIFE_SUPPORT,
        manufacturer: 'Getinge',
        model: 'Cardiohelp',
        serialNumber: 'ECMO-RCH-2024-D004',
        location: { id: 'RCH-L4', building: 'Main Hospital', floor: '4', room: 'Cardiac ICU' },
        department: 'Intensive Care',
        status: EquipmentStatus.IN_SERVICE,
        condition: EquipmentCondition.GOOD,
        riskLevel: RiskLevel.HIGH,
        purchaseDate: new Date('2024-02-01'),
        installationDate: new Date('2024-02-15'),
        warrantyExpiry: new Date('2027-02-01'),
        lastMaintenanceDate: new Date('2024-11-20'),
        nextMaintenanceDate: new Date('2025-02-20'),
        purchaseCost: 185000,
        currentValue: 175000,
        powerRequirements: '220V, 30A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        createdAt: new Date('2024-02-01'),
        updatedAt: new Date('2024-11-20')
      },
      {
        id: 'EQ-RCH-005',
        tenantId: 'tenant-4',
        inventoryNumber: 'RCH-2024-005',
        name: 'PET/CT Scanner',
        type: EquipmentType.IMAGING,
        category: EquipmentCategory.MONITORING_SURGICAL_ICU,
        manufacturer: 'Siemens Healthineers',
        model: 'Biograph Vision',
        serialNumber: 'PETCT-RCH-2024-E005',
        location: { id: 'RCH-L5', building: 'Imaging Center', floor: '1', room: 'Nuclear Medicine' },
        department: 'Radiology',
        status: EquipmentStatus.OUT_OF_SERVICE,
        condition: EquipmentCondition.POOR,
        riskLevel: RiskLevel.HIGH,
        purchaseDate: new Date('2021-04-01'),
        installationDate: new Date('2021-06-01'),
        warrantyExpiry: new Date('2024-04-01'),
        lastMaintenanceDate: new Date('2024-10-01'),
        nextMaintenanceDate: new Date('2025-01-01'),
        purchaseCost: 3200000,
        currentValue: 1800000,
        powerRequirements: '480V, 150A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        notes: 'Detector failure - awaiting vendor assessment for repair vs replacement',
        createdAt: new Date('2021-04-01'),
        updatedAt: new Date('2024-10-01')
      },
      {
        id: 'EQ-RCH-006',
        tenantId: 'tenant-4',
        inventoryNumber: 'RCH-2024-006',
        name: 'Cardiac Ultrasound',
        type: EquipmentType.DIAGNOSTIC,
        category: EquipmentCategory.MONITORING_PHYSIOLOGICAL,
        manufacturer: 'Philips Healthcare',
        model: 'EPIQ CVx',
        serialNumber: 'ECHO-RCH-2024-F006',
        location: { id: 'RCH-L6', building: 'Heart Center', floor: '2', room: 'Echo Lab 1' },
        department: 'Cardiology',
        status: EquipmentStatus.IN_SERVICE,
        condition: EquipmentCondition.EXCELLENT,
        riskLevel: RiskLevel.MEDIUM,
        purchaseDate: new Date('2024-05-01'),
        installationDate: new Date('2024-05-15'),
        warrantyExpiry: new Date('2027-05-01'),
        lastMaintenanceDate: new Date('2024-11-15'),
        nextMaintenanceDate: new Date('2025-05-15'),
        purchaseCost: 195000,
        currentValue: 190000,
        powerRequirements: '110V, 15A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        createdAt: new Date('2024-05-01'),
        updatedAt: new Date('2024-11-15')
      },
      {
        id: 'EQ-RCH-007',
        tenantId: 'tenant-4',
        inventoryNumber: 'RCH-2024-007',
        name: 'Neonatal Incubator',
        type: EquipmentType.LIFE_SUPPORT,
        category: EquipmentCategory.LIFE_SUPPORT,
        manufacturer: 'Dräger',
        model: 'Caleo',
        serialNumber: 'INC-RCH-2024-G007',
        location: { id: 'RCH-L7', building: 'Main Hospital', floor: '5', room: 'NICU Bay 3' },
        department: 'Neonatal Care',
        status: EquipmentStatus.IN_SERVICE,
        condition: EquipmentCondition.GOOD,
        riskLevel: RiskLevel.HIGH,
        purchaseDate: new Date('2023-11-01'),
        installationDate: new Date('2023-11-15'),
        warrantyExpiry: new Date('2026-11-01'),
        lastMaintenanceDate: new Date('2024-08-15'),
        nextMaintenanceDate: new Date('2025-02-15'),
        purchaseCost: 42000,
        currentValue: 38000,
        powerRequirements: '110V, 15A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        createdAt: new Date('2023-11-01'),
        updatedAt: new Date('2024-08-15')
      },
      {
        id: 'EQ-RCH-008',
        tenantId: 'tenant-4',
        inventoryNumber: 'RCH-2024-008',
        name: 'Chemistry Analyzer',
        type: EquipmentType.LABORATORY,
        category: EquipmentCategory.LABORATORY_ANALYTICAL,
        manufacturer: 'Roche',
        model: 'cobas 8000',
        serialNumber: 'CHEM-RCH-2024-H008',
        location: { id: 'RCH-L8', building: 'Laboratory Building', floor: '1', room: 'Core Lab' },
        department: 'Laboratory',
        status: EquipmentStatus.IN_SERVICE,
        condition: EquipmentCondition.EXCELLENT,
        riskLevel: RiskLevel.LOW,
        purchaseDate: new Date('2024-01-15'),
        installationDate: new Date('2024-02-01'),
        warrantyExpiry: new Date('2029-01-15'),
        lastMaintenanceDate: new Date('2024-10-01'),
        nextMaintenanceDate: new Date('2025-04-01'),
        purchaseCost: 680000,
        currentValue: 650000,
        powerRequirements: '220V, 40A',
        operatingManualAvailable: true,
        serviceManualAvailable: true,
        createdAt: new Date('2024-01-15'),
        updatedAt: new Date('2024-10-01')
      }
    ];
  }
  
  private generateInventoryData(): InventoryItem[] {
    return [
      {
        id: 'INV001',
        tenantId: 'tenant-1',
        sku: 'CON-ECG-001',
        name: 'ECG Electrodes (Pack of 100)',
        category: InventoryCategory.CONSUMABLES,
        type: InventoryType.MEDICAL_SUPPLIES,
        quantity: 450,
        minQuantity: 100,
        maxQuantity: 1000,
        reorderLevel: 200,
        unitOfMeasure: 'Pack',
        unitCost: 25,
        totalValue: 11250,
        location: 'Storage Room A-1',
        expiryDate: new Date('2026-06-30'),
        lotNumber: 'LOT-2024-A001',
        lastRestockDate: new Date('2024-12-01'),
        status: StockStatus.IN_STOCK,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-12-01')
      },
      {
        id: 'INV002',
        tenantId: 'tenant-1',
        sku: 'CON-SYR-002',
        name: 'Disposable Syringes 10ml (Box of 100)',
        category: InventoryCategory.CONSUMABLES,
        type: InventoryType.MEDICAL_SUPPLIES,
        quantity: 85,
        minQuantity: 50,
        maxQuantity: 500,
        reorderLevel: 100,
        unitOfMeasure: 'Box',
        unitCost: 18,
        totalValue: 1530,
        location: 'Storage Room A-2',
        expiryDate: new Date('2027-03-15'),
        lotNumber: 'LOT-2024-B002',
        lastRestockDate: new Date('2024-11-15'),
        status: StockStatus.LOW_STOCK,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-11-15')
      },
      {
        id: 'INV003',
        tenantId: 'tenant-1',
        sku: 'SPR-VEN-001',
        name: 'Ventilator Breathing Circuit',
        category: InventoryCategory.SPARE_PARTS,
        type: InventoryType.MAINTENANCE_PARTS,
        quantity: 25,
        minQuantity: 10,
        maxQuantity: 100,
        reorderLevel: 15,
        unitOfMeasure: 'Unit',
        unitCost: 150,
        totalValue: 3750,
        location: 'Parts Storage B-1',
        lastRestockDate: new Date('2024-10-20'),
        status: StockStatus.IN_STOCK,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-10-20')
      },
      {
        id: 'INV004',
        tenantId: 'tenant-1',
        sku: 'REA-CBC-001',
        name: 'CBC Reagent Kit',
        category: InventoryCategory.REAGENTS,
        type: InventoryType.LABORATORY_SUPPLIES,
        quantity: 12,
        minQuantity: 5,
        maxQuantity: 30,
        reorderLevel: 8,
        unitOfMeasure: 'Kit',
        unitCost: 350,
        totalValue: 4200,
        location: 'Lab Storage L-1',
        expiryDate: new Date('2025-04-30'),
        lotNumber: 'LOT-2024-C003',
        lastRestockDate: new Date('2024-09-01'),
        status: StockStatus.IN_STOCK,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-09-01')
      },
      {
        id: 'INV005',
        tenantId: 'tenant-1',
        sku: 'CON-GLV-001',
        name: 'Nitrile Gloves Medium (Box of 100)',
        category: InventoryCategory.CONSUMABLES,
        type: InventoryType.MEDICAL_SUPPLIES,
        quantity: 0,
        minQuantity: 50,
        maxQuantity: 500,
        reorderLevel: 100,
        unitOfMeasure: 'Box',
        unitCost: 12,
        totalValue: 0,
        location: 'Storage Room A-1',
        lastRestockDate: new Date('2024-10-01'),
        status: StockStatus.OUT_OF_STOCK,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2025-01-15')
      },
      {
        id: 'INV006',
        tenantId: 'tenant-1',
        sku: 'SPR-MON-002',
        name: 'SpO2 Sensor Cable',
        category: InventoryCategory.ACCESSORIES,
        type: InventoryType.MAINTENANCE_PARTS,
        quantity: 18,
        minQuantity: 5,
        maxQuantity: 50,
        reorderLevel: 10,
        unitOfMeasure: 'Unit',
        unitCost: 85,
        totalValue: 1530,
        location: 'Parts Storage B-2',
        lastRestockDate: new Date('2024-11-01'),
        status: StockStatus.IN_STOCK,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-11-01')
      },
      {
        id: 'INV007',
        tenantId: 'tenant-1',
        sku: 'CON-BLD-001',
        name: 'Blood Collection Tubes (Pack of 100)',
        category: InventoryCategory.CONSUMABLES,
        type: InventoryType.LABORATORY_SUPPLIES,
        quantity: 220,
        minQuantity: 100,
        maxQuantity: 500,
        reorderLevel: 150,
        unitOfMeasure: 'Pack',
        unitCost: 45,
        totalValue: 9900,
        location: 'Lab Storage L-2',
        expiryDate: new Date('2025-12-31'),
        lotNumber: 'LOT-2024-D004',
        lastRestockDate: new Date('2024-12-10'),
        status: StockStatus.IN_STOCK,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-12-10')
      },
      {
        id: 'INV008',
        tenantId: 'tenant-1',
        sku: 'SPR-DEF-001',
        name: 'Defibrillator Pads (Adult)',
        category: InventoryCategory.CONSUMABLES,
        type: InventoryType.MEDICAL_SUPPLIES,
        quantity: 35,
        minQuantity: 20,
        maxQuantity: 100,
        reorderLevel: 30,
        unitOfMeasure: 'Pair',
        unitCost: 75,
        totalValue: 2625,
        location: 'Emergency Storage E-1',
        expiryDate: new Date('2026-08-15'),
        lotNumber: 'LOT-2024-E005',
        lastRestockDate: new Date('2024-08-15'),
        status: StockStatus.IN_STOCK,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-08-15')
      },
      // ============ Sunrise Medical Center (tenant-2) Inventory ============
      {
        id: 'INV-SMC-001',
        tenantId: 'tenant-2',
        sku: 'SMC-CON-001',
        name: 'CT Contrast Media (Iohexol)',
        category: InventoryCategory.REAGENTS,
        type: InventoryType.MEDICAL_SUPPLIES,
        quantity: 45,
        minQuantity: 20,
        maxQuantity: 100,
        reorderLevel: 30,
        unitOfMeasure: 'Bottle (350ml)',
        unitCost: 125,
        totalValue: 5625,
        location: 'Radiology Storage R-1',
        expiryDate: new Date('2026-03-30'),
        lotNumber: 'SMC-LOT-2024-A001',
        lastRestockDate: new Date('2024-12-01'),
        status: StockStatus.IN_STOCK,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-12-01')
      },
      {
        id: 'INV-SMC-002',
        tenantId: 'tenant-2',
        sku: 'SMC-CON-002',
        name: 'Dialysis Tubing Set',
        category: InventoryCategory.CONSUMABLES,
        type: InventoryType.MEDICAL_SUPPLIES,
        quantity: 18,
        minQuantity: 25,
        maxQuantity: 100,
        reorderLevel: 30,
        unitOfMeasure: 'Set',
        unitCost: 85,
        totalValue: 1530,
        location: 'Dialysis Storage D-1',
        expiryDate: new Date('2026-06-30'),
        lotNumber: 'SMC-LOT-2024-B002',
        lastRestockDate: new Date('2024-11-01'),
        status: StockStatus.LOW_STOCK,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-11-01')
      },
      {
        id: 'INV-SMC-003',
        tenantId: 'tenant-2',
        sku: 'SMC-SPR-001',
        name: 'Surgical Microscope Light Bulb',
        category: InventoryCategory.SPARE_PARTS,
        type: InventoryType.MAINTENANCE_PARTS,
        quantity: 8,
        minQuantity: 5,
        maxQuantity: 20,
        reorderLevel: 6,
        unitOfMeasure: 'Unit',
        unitCost: 450,
        totalValue: 3600,
        location: 'Parts Storage P-2',
        lastRestockDate: new Date('2024-09-15'),
        status: StockStatus.IN_STOCK,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-09-15')
      },
      {
        id: 'INV-SMC-004',
        tenantId: 'tenant-2',
        sku: 'SMC-CON-003',
        name: 'Mammography Film (Box of 100)',
        category: InventoryCategory.CONSUMABLES,
        type: InventoryType.MEDICAL_SUPPLIES,
        quantity: 0,
        minQuantity: 10,
        maxQuantity: 50,
        reorderLevel: 15,
        unitOfMeasure: 'Box',
        unitCost: 280,
        totalValue: 0,
        location: 'Women\'s Center Storage W-1',
        lastRestockDate: new Date('2024-10-01'),
        status: StockStatus.OUT_OF_STOCK,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2025-01-15')
      },
      {
        id: 'INV-SMC-005',
        tenantId: 'tenant-2',
        sku: 'SMC-REA-001',
        name: 'Blood Gas Cartridge',
        category: InventoryCategory.REAGENTS,
        type: InventoryType.LABORATORY_SUPPLIES,
        quantity: 24,
        minQuantity: 10,
        maxQuantity: 50,
        reorderLevel: 15,
        unitOfMeasure: 'Cartridge',
        unitCost: 95,
        totalValue: 2280,
        location: 'Lab Storage L-1',
        expiryDate: new Date('2025-08-30'),
        lotNumber: 'SMC-LOT-2024-C003',
        lastRestockDate: new Date('2024-12-10'),
        status: StockStatus.IN_STOCK,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-12-10')
      },
      // ============ Riverside Community Hospital (tenant-4) Inventory ============
      {
        id: 'INV-RCH-001',
        tenantId: 'tenant-4',
        sku: 'RCH-CON-001',
        name: 'MRI Contrast Agent (Gadolinium)',
        category: InventoryCategory.REAGENTS,
        type: InventoryType.MEDICAL_SUPPLIES,
        quantity: 85,
        minQuantity: 30,
        maxQuantity: 150,
        reorderLevel: 50,
        unitOfMeasure: 'Vial (20ml)',
        unitCost: 180,
        totalValue: 15300,
        location: 'MRI Suite Storage M-1',
        expiryDate: new Date('2026-09-30'),
        lotNumber: 'RCH-LOT-2024-A001',
        lastRestockDate: new Date('2024-12-15'),
        status: StockStatus.IN_STOCK,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-12-15')
      },
      {
        id: 'INV-RCH-002',
        tenantId: 'tenant-4',
        sku: 'RCH-CON-002',
        name: 'ECMO Oxygenator',
        category: InventoryCategory.CONSUMABLES,
        type: InventoryType.MEDICAL_SUPPLIES,
        quantity: 12,
        minQuantity: 8,
        maxQuantity: 30,
        reorderLevel: 10,
        unitOfMeasure: 'Unit',
        unitCost: 2500,
        totalValue: 30000,
        location: 'Cardiac ICU Storage C-1',
        expiryDate: new Date('2025-12-31'),
        lotNumber: 'RCH-LOT-2024-B002',
        lastRestockDate: new Date('2024-11-01'),
        status: StockStatus.IN_STOCK,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-11-01')
      },
      {
        id: 'INV-RCH-003',
        tenantId: 'tenant-4',
        sku: 'RCH-SPR-001',
        name: 'Da Vinci Instrument Tip Cover',
        category: InventoryCategory.ACCESSORIES,
        type: InventoryType.MAINTENANCE_PARTS,
        quantity: 6,
        minQuantity: 10,
        maxQuantity: 40,
        reorderLevel: 12,
        unitOfMeasure: 'Set',
        unitCost: 1200,
        totalValue: 7200,
        location: 'Surgery Center Storage S-1',
        lastRestockDate: new Date('2024-10-15'),
        status: StockStatus.LOW_STOCK,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-10-15')
      },
      {
        id: 'INV-RCH-004',
        tenantId: 'tenant-4',
        sku: 'RCH-REA-001',
        name: 'Comprehensive Metabolic Panel Reagent',
        category: InventoryCategory.REAGENTS,
        type: InventoryType.LABORATORY_SUPPLIES,
        quantity: 28,
        minQuantity: 15,
        maxQuantity: 60,
        reorderLevel: 20,
        unitOfMeasure: 'Kit',
        unitCost: 520,
        totalValue: 14560,
        location: 'Core Lab Storage CL-1',
        expiryDate: new Date('2025-06-30'),
        lotNumber: 'RCH-LOT-2024-C003',
        lastRestockDate: new Date('2024-12-01'),
        status: StockStatus.IN_STOCK,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-12-01')
      },
      {
        id: 'INV-RCH-005',
        tenantId: 'tenant-4',
        sku: 'RCH-CON-003',
        name: 'Neonatal Feeding Tubes',
        category: InventoryCategory.CONSUMABLES,
        type: InventoryType.MEDICAL_SUPPLIES,
        quantity: 150,
        minQuantity: 50,
        maxQuantity: 300,
        reorderLevel: 80,
        unitOfMeasure: 'Pack of 10',
        unitCost: 35,
        totalValue: 5250,
        location: 'NICU Storage N-1',
        expiryDate: new Date('2027-03-15'),
        lotNumber: 'RCH-LOT-2024-D004',
        lastRestockDate: new Date('2024-11-20'),
        status: StockStatus.IN_STOCK,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-11-20')
      },
      {
        id: 'INV-RCH-006',
        tenantId: 'tenant-4',
        sku: 'RCH-SPR-002',
        name: 'Linear Accelerator Beam Filter',
        category: InventoryCategory.SPARE_PARTS,
        type: InventoryType.MAINTENANCE_PARTS,
        quantity: 4,
        minQuantity: 2,
        maxQuantity: 10,
        reorderLevel: 3,
        unitOfMeasure: 'Unit',
        unitCost: 8500,
        totalValue: 34000,
        location: 'Oncology Parts Storage O-1',
        lastRestockDate: new Date('2024-08-01'),
        status: StockStatus.IN_STOCK,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-08-01')
      },
      {
        id: 'INV-RCH-007',
        tenantId: 'tenant-4',
        sku: 'RCH-CON-004',
        name: 'PET Radiotracer (FDG)',
        category: InventoryCategory.REAGENTS,
        type: InventoryType.MEDICAL_SUPPLIES,
        quantity: 0,
        minQuantity: 5,
        maxQuantity: 20,
        reorderLevel: 8,
        unitOfMeasure: 'Dose',
        unitCost: 450,
        totalValue: 0,
        location: 'Nuclear Medicine Hot Lab',
        lastRestockDate: new Date('2024-12-20'),
        status: StockStatus.OUT_OF_STOCK,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2025-01-25')
      }
    ];
  }
  
  private generateMaintenanceData(): MaintenanceRecord[] {
    return [
      {
        id: 'MNT001',
        tenantId: 'tenant-1',
        equipmentId: 'EQ001',
        type: MaintenanceType.PREVENTIVE,
        status: MaintenanceStatus.COMPLETED,
        scheduledDate: new Date('2024-12-01'),
        completedDate: new Date('2024-12-01'),
        technician: 'Michael Chen',
        description: 'Quarterly preventive maintenance',
        findings: 'All systems functioning normally. Calibration verified.',
        cost: 450,
        nextScheduledDate: new Date('2025-03-01'),
        createdAt: new Date('2024-11-15'),
        updatedAt: new Date('2024-12-01')
      },
      {
        id: 'MNT002',
        tenantId: 'tenant-1',
        equipmentId: 'EQ003',
        type: MaintenanceType.CORRECTIVE,
        status: MaintenanceStatus.IN_PROGRESS,
        scheduledDate: new Date('2025-01-10'),
        technician: 'Michael Chen',
        description: 'Alarm system malfunction repair',
        createdAt: new Date('2025-01-08'),
        updatedAt: new Date('2025-01-10')
      },
      {
        id: 'MNT003',
        tenantId: 'tenant-1',
        equipmentId: 'EQ002',
        type: MaintenanceType.CALIBRATION,
        status: MaintenanceStatus.SCHEDULED,
        scheduledDate: new Date('2025-02-15'),
        description: 'Annual calibration check',
        createdAt: new Date('2025-01-01'),
        updatedAt: new Date('2025-01-01')
      },
      {
        id: 'MNT004',
        tenantId: 'tenant-1',
        equipmentId: 'EQ008',
        type: MaintenanceType.CORRECTIVE,
        status: MaintenanceStatus.OVERDUE,
        scheduledDate: new Date('2024-11-01'),
        description: 'Display repair - component replacement needed',
        findings: 'Display module needs complete replacement',
        createdAt: new Date('2024-08-01'),
        updatedAt: new Date('2024-11-15')
      },
      {
        id: 'MNT005',
        tenantId: 'tenant-1',
        equipmentId: 'EQ007',
        type: MaintenanceType.SAFETY_INSPECTION,
        status: MaintenanceStatus.COMPLETED,
        scheduledDate: new Date('2024-12-15'),
        completedDate: new Date('2024-12-15'),
        technician: 'Sarah Johnson',
        description: 'Annual safety inspection and certification',
        findings: 'Passed all safety requirements. Certificate renewed.',
        cost: 650,
        nextScheduledDate: new Date('2025-12-15'),
        createdAt: new Date('2024-12-01'),
        updatedAt: new Date('2024-12-15')
      },
      // ============ Sunrise Medical Center (tenant-2) Maintenance ============
      {
        id: 'MNT-SMC-001',
        tenantId: 'tenant-2',
        equipmentId: 'EQ-SMC-001',
        type: MaintenanceType.PREVENTIVE,
        status: MaintenanceStatus.COMPLETED,
        scheduledDate: new Date('2024-11-15'),
        completedDate: new Date('2024-11-15'),
        technician: 'David Lee',
        description: 'CT Scanner quarterly tube calibration',
        findings: 'Tube output within specifications. No issues found.',
        cost: 1250,
        nextScheduledDate: new Date('2025-02-15'),
        createdAt: new Date('2024-11-01'),
        updatedAt: new Date('2024-11-15')
      },
      {
        id: 'MNT-SMC-002',
        tenantId: 'tenant-2',
        equipmentId: 'EQ-SMC-004',
        type: MaintenanceType.CORRECTIVE,
        status: MaintenanceStatus.IN_PROGRESS,
        scheduledDate: new Date('2025-01-20'),
        technician: 'Ana Garcia',
        description: 'Dialysis machine pump replacement',
        createdAt: new Date('2025-01-18'),
        updatedAt: new Date('2025-01-20')
      },
      {
        id: 'MNT-SMC-003',
        tenantId: 'tenant-2',
        equipmentId: 'EQ-SMC-003',
        type: MaintenanceType.CALIBRATION,
        status: MaintenanceStatus.SCHEDULED,
        scheduledDate: new Date('2025-01-15'),
        description: 'Cath Lab image intensifier calibration',
        createdAt: new Date('2025-01-01'),
        updatedAt: new Date('2025-01-01')
      },
      // ============ Riverside Community Hospital (tenant-4) Maintenance ============
      {
        id: 'MNT-RCH-001',
        tenantId: 'tenant-4',
        equipmentId: 'EQ-RCH-001',
        type: MaintenanceType.PREVENTIVE,
        status: MaintenanceStatus.COMPLETED,
        scheduledDate: new Date('2024-12-01'),
        completedDate: new Date('2024-12-01'),
        technician: 'Michael Brown',
        description: 'MRI cryogen level check and magnet calibration',
        findings: 'Helium levels optimal. Magnet homogeneity excellent.',
        cost: 3500,
        nextScheduledDate: new Date('2025-03-01'),
        createdAt: new Date('2024-11-15'),
        updatedAt: new Date('2024-12-01')
      },
      {
        id: 'MNT-RCH-002',
        tenantId: 'tenant-4',
        equipmentId: 'EQ-RCH-005',
        type: MaintenanceType.CORRECTIVE,
        status: MaintenanceStatus.OVERDUE,
        scheduledDate: new Date('2024-10-15'),
        description: 'PET/CT detector array repair - critical failure',
        findings: 'Multiple detector modules non-functional. Vendor assessment pending.',
        createdAt: new Date('2024-10-01'),
        updatedAt: new Date('2024-11-15')
      },
      {
        id: 'MNT-RCH-003',
        tenantId: 'tenant-4',
        equipmentId: 'EQ-RCH-002',
        type: MaintenanceType.SAFETY_INSPECTION,
        status: MaintenanceStatus.COMPLETED,
        scheduledDate: new Date('2024-11-01'),
        completedDate: new Date('2024-11-01'),
        technician: 'Emily Williams',
        description: 'Linear Accelerator annual radiation safety survey',
        findings: 'All shielding adequate. Beam alignment within tolerance.',
        cost: 4500,
        nextScheduledDate: new Date('2025-11-01'),
        createdAt: new Date('2024-10-15'),
        updatedAt: new Date('2024-11-01')
      },
      {
        id: 'MNT-RCH-004',
        tenantId: 'tenant-4',
        equipmentId: 'EQ-RCH-003',
        type: MaintenanceType.PREVENTIVE,
        status: MaintenanceStatus.SCHEDULED,
        scheduledDate: new Date('2025-03-15'),
        description: 'Da Vinci Robot annual service and instrument calibration',
        createdAt: new Date('2025-01-01'),
        updatedAt: new Date('2025-01-01')
      }
    ];
  }
  
  private generateWorkOrderData(): WorkOrder[] {
    return [
      {
        id: 'WO001',
        tenantId: 'tenant-1',
        workOrderNumber: 'WO-2025-001',
        equipmentId: 'EQ003',
        type: WorkOrderType.REPAIR,
        priority: WorkOrderPriority.HIGH,
        status: WorkOrderStatus.IN_PROGRESS,
        requestedBy: 'Dr. Amanda Torres',
        requestedDate: new Date('2025-01-08'),
        assignedTo: 'Michael Chen',
        scheduledDate: new Date('2025-01-10'),
        description: 'Ventilator alarm system not functioning correctly',
        createdAt: new Date('2025-01-08'),
        updatedAt: new Date('2025-01-10')
      },
      {
        id: 'WO002',
        tenantId: 'tenant-1',
        workOrderNumber: 'WO-2025-002',
        equipmentId: 'EQ008',
        type: WorkOrderType.REPAIR,
        priority: WorkOrderPriority.MEDIUM,
        status: WorkOrderStatus.ON_HOLD,
        requestedBy: 'Nurse Jennifer Walsh',
        requestedDate: new Date('2024-08-01'),
        description: 'ECG display showing artifacts - needs evaluation',
        resolution: 'Awaiting replacement parts from vendor',
        createdAt: new Date('2024-08-01'),
        updatedAt: new Date('2024-11-15')
      },
      {
        id: 'WO003',
        tenantId: 'tenant-1',
        workOrderNumber: 'WO-2025-003',
        equipmentId: 'EQ005',
        type: WorkOrderType.MAINTENANCE,
        priority: WorkOrderPriority.LOW,
        status: WorkOrderStatus.OPEN,
        requestedBy: 'Biomedical Engineering',
        requestedDate: new Date('2025-01-15'),
        scheduledDate: new Date('2025-02-01'),
        description: 'Scheduled probe cleaning and calibration',
        createdAt: new Date('2025-01-15'),
        updatedAt: new Date('2025-01-15')
      },
      {
        id: 'WO004',
        tenantId: 'tenant-1',
        workOrderNumber: 'WO-2024-048',
        equipmentId: 'EQ001',
        type: WorkOrderType.MAINTENANCE,
        priority: WorkOrderPriority.MEDIUM,
        status: WorkOrderStatus.COMPLETED,
        requestedBy: 'Biomedical Engineering',
        requestedDate: new Date('2024-11-15'),
        assignedTo: 'Michael Chen',
        scheduledDate: new Date('2024-12-01'),
        completedDate: new Date('2024-12-01'),
        description: 'Quarterly preventive maintenance',
        resolution: 'All checks completed successfully',
        laborHours: 3,
        partsCost: 150,
        totalCost: 450,
        createdAt: new Date('2024-11-15'),
        updatedAt: new Date('2024-12-01')
      },
      // ============ Sunrise Medical Center (tenant-2) Work Orders ============
      {
        id: 'WO-SMC-001',
        tenantId: 'tenant-2',
        workOrderNumber: 'SMC-WO-2025-001',
        equipmentId: 'EQ-SMC-004',
        type: WorkOrderType.REPAIR,
        priority: WorkOrderPriority.HIGH,
        status: WorkOrderStatus.IN_PROGRESS,
        requestedBy: 'Dialysis Unit Charge Nurse',
        requestedDate: new Date('2025-01-18'),
        assignedTo: 'Ana Garcia',
        scheduledDate: new Date('2025-01-20'),
        description: 'Dialysis pump making unusual noise and flow rate fluctuating',
        createdAt: new Date('2025-01-18'),
        updatedAt: new Date('2025-01-20')
      },
      {
        id: 'WO-SMC-002',
        tenantId: 'tenant-2',
        workOrderNumber: 'SMC-WO-2025-002',
        equipmentId: 'EQ-SMC-002',
        type: WorkOrderType.MAINTENANCE,
        priority: WorkOrderPriority.MEDIUM,
        status: WorkOrderStatus.OPEN,
        requestedBy: 'Biomedical Engineering',
        requestedDate: new Date('2025-01-15'),
        scheduledDate: new Date('2025-02-01'),
        description: 'Scheduled detector calibration for mammography system',
        createdAt: new Date('2025-01-15'),
        updatedAt: new Date('2025-01-15')
      },
      {
        id: 'WO-SMC-003',
        tenantId: 'tenant-2',
        workOrderNumber: 'SMC-WO-2024-089',
        equipmentId: 'EQ-SMC-001',
        type: WorkOrderType.MAINTENANCE,
        priority: WorkOrderPriority.MEDIUM,
        status: WorkOrderStatus.COMPLETED,
        requestedBy: 'Radiology Department',
        requestedDate: new Date('2024-11-01'),
        assignedTo: 'David Lee',
        scheduledDate: new Date('2024-11-15'),
        completedDate: new Date('2024-11-15'),
        description: 'CT Scanner quarterly maintenance and tube calibration',
        resolution: 'All parameters within specification',
        laborHours: 6,
        partsCost: 850,
        totalCost: 1250,
        createdAt: new Date('2024-11-01'),
        updatedAt: new Date('2024-11-15')
      },
      // ============ Riverside Community Hospital (tenant-4) Work Orders ============
      {
        id: 'WO-RCH-001',
        tenantId: 'tenant-4',
        workOrderNumber: 'RCH-WO-2025-001',
        equipmentId: 'EQ-RCH-005',
        type: WorkOrderType.REPAIR,
        priority: WorkOrderPriority.CRITICAL,
        status: WorkOrderStatus.ON_HOLD,
        requestedBy: 'Nuclear Medicine Director',
        requestedDate: new Date('2024-10-01'),
        description: 'PET/CT detector failure - multiple modules non-functional',
        resolution: 'Awaiting vendor assessment for repair vs replacement decision',
        createdAt: new Date('2024-10-01'),
        updatedAt: new Date('2025-01-15')
      },
      {
        id: 'WO-RCH-002',
        tenantId: 'tenant-4',
        workOrderNumber: 'RCH-WO-2025-002',
        equipmentId: 'EQ-RCH-003',
        type: WorkOrderType.MAINTENANCE,
        priority: WorkOrderPriority.MEDIUM,
        status: WorkOrderStatus.OPEN,
        requestedBy: 'Biomedical Engineering',
        requestedDate: new Date('2025-01-10'),
        scheduledDate: new Date('2025-03-15'),
        description: 'Da Vinci Robot scheduled annual service',
        createdAt: new Date('2025-01-10'),
        updatedAt: new Date('2025-01-10')
      },
      {
        id: 'WO-RCH-003',
        tenantId: 'tenant-4',
        workOrderNumber: 'RCH-WO-2025-003',
        equipmentId: 'EQ-RCH-001',
        type: WorkOrderType.MAINTENANCE,
        priority: WorkOrderPriority.HIGH,
        status: WorkOrderStatus.IN_PROGRESS,
        requestedBy: 'MRI Department',
        requestedDate: new Date('2025-01-22'),
        assignedTo: 'Michael Brown',
        scheduledDate: new Date('2025-01-25'),
        description: 'MRI coil showing intermittent signal issues',
        createdAt: new Date('2025-01-22'),
        updatedAt: new Date('2025-01-25')
      },
      {
        id: 'WO-RCH-004',
        tenantId: 'tenant-4',
        workOrderNumber: 'RCH-WO-2024-156',
        equipmentId: 'EQ-RCH-002',
        type: WorkOrderType.INSPECTION,
        priority: WorkOrderPriority.HIGH,
        status: WorkOrderStatus.COMPLETED,
        requestedBy: 'Radiation Safety Officer',
        requestedDate: new Date('2024-10-15'),
        assignedTo: 'Emily Williams',
        scheduledDate: new Date('2024-11-01'),
        completedDate: new Date('2024-11-01'),
        description: 'Annual radiation safety survey for Linear Accelerator',
        resolution: 'All safety parameters passed. Certification renewed.',
        laborHours: 8,
        partsCost: 0,
        totalCost: 4500,
        createdAt: new Date('2024-10-15'),
        updatedAt: new Date('2024-11-01')
      }
    ];
  }
  
  private generateVendorData(): Vendor[] {
    return [
      {
        id: 'VEN001',
        tenantId: 'tenant-1',
        name: 'GE Healthcare India',
        contactPerson: 'Rajesh Kumar',
        email: 'rajesh.kumar@gehealthcare.com',
        phone: '+91 80 4128 5000',
        address: '122, Airport Road',
        city: 'Bangalore',
        country: 'India',
        category: VendorCategory.EQUIPMENT_MANUFACTURER,
        rating: 4.5,
        contractStartDate: new Date('2023-01-01'),
        contractEndDate: new Date('2025-12-31'),
        paymentTerms: 'Net 30',
        isActive: true,
        createdAt: new Date('2023-01-01'),
        updatedAt: new Date('2024-06-15')
      },
      {
        id: 'VEN002',
        tenantId: 'tenant-1',
        name: 'Philips India Healthcare',
        contactPerson: 'Priya Sharma',
        email: 'priya.sharma@philips.com',
        phone: '+91 124 466 5000',
        address: 'DLF Cyber City, Phase 3',
        city: 'Gurgaon',
        country: 'India',
        category: VendorCategory.EQUIPMENT_MANUFACTURER,
        rating: 4.8,
        contractStartDate: new Date('2022-06-01'),
        contractEndDate: new Date('2025-05-31'),
        paymentTerms: 'Net 45',
        isActive: true,
        createdAt: new Date('2022-06-01'),
        updatedAt: new Date('2024-08-20')
      },
      {
        id: 'VEN003',
        tenantId: 'tenant-1',
        name: 'MedSupply India Pvt Ltd',
        contactPerson: 'Amit Patel',
        email: 'amit.patel@medsupply.in',
        phone: '+91 22 2556 7890',
        address: '45, Industrial Area',
        city: 'Mumbai',
        country: 'India',
        category: VendorCategory.CONSUMABLES_SUPPLIER,
        rating: 4.2,
        paymentTerms: 'Net 15',
        isActive: true,
        createdAt: new Date('2023-03-15'),
        updatedAt: new Date('2024-10-10')
      },
      {
        id: 'VEN004',
        tenantId: 'tenant-1',
        name: 'BioTech Solutions',
        contactPerson: 'Dr. Meera Iyer',
        email: 'meera@biotechsolutions.in',
        phone: '+91 44 2834 5678',
        address: 'Tech Park, Velachery',
        city: 'Chennai',
        country: 'India',
        category: VendorCategory.SERVICE_PROVIDER,
        rating: 4.6,
        contractStartDate: new Date('2024-01-01'),
        contractEndDate: new Date('2024-12-31'),
        paymentTerms: 'Net 30',
        isActive: true,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-07-15')
      },
      // ============ Sunrise Medical Center (tenant-2) Vendors ============
      {
        id: 'VEN-SMC-001',
        tenantId: 'tenant-2',
        name: 'Siemens Healthineers West',
        contactPerson: 'Mark Thompson',
        email: 'mark.thompson@siemens-healthineers.com',
        phone: '(858) 555-0100',
        address: '5755 Oberlin Drive',
        city: 'San Diego',
        country: 'USA',
        category: VendorCategory.EQUIPMENT_MANUFACTURER,
        rating: 4.7,
        contractStartDate: new Date('2023-01-01'),
        contractEndDate: new Date('2026-12-31'),
        paymentTerms: 'Net 45',
        isActive: true,
        createdAt: new Date('2023-01-01'),
        updatedAt: new Date('2024-08-15')
      },
      {
        id: 'VEN-SMC-002',
        tenantId: 'tenant-2',
        name: 'Pacific Medical Supplies',
        contactPerson: 'Jennifer Wu',
        email: 'jwu@pacificmedical.com',
        phone: '(619) 555-0200',
        address: '1234 Commerce St',
        city: 'San Diego',
        country: 'USA',
        category: VendorCategory.CONSUMABLES_SUPPLIER,
        rating: 4.3,
        paymentTerms: 'Net 30',
        isActive: true,
        createdAt: new Date('2023-06-01'),
        updatedAt: new Date('2024-11-01')
      },
      {
        id: 'VEN-SMC-003',
        tenantId: 'tenant-2',
        name: 'Fresenius Medical Care',
        contactPerson: 'Carlos Rodriguez',
        email: 'carlos.rodriguez@fmc-na.com',
        phone: '(800) 555-0300',
        address: '920 Winter Street',
        city: 'Waltham',
        country: 'USA',
        category: VendorCategory.EQUIPMENT_MANUFACTURER,
        rating: 4.5,
        contractStartDate: new Date('2022-01-01'),
        contractEndDate: new Date('2025-12-31'),
        paymentTerms: 'Net 60',
        isActive: true,
        createdAt: new Date('2022-01-01'),
        updatedAt: new Date('2024-06-15')
      },
      // ============ Riverside Community Hospital (tenant-4) Vendors ============
      {
        id: 'VEN-RCH-001',
        tenantId: 'tenant-4',
        name: 'GE Healthcare Central',
        contactPerson: 'Robert Anderson',
        email: 'robert.anderson@gehealthcare.com',
        phone: '(312) 555-0100',
        address: '500 W Monroe St',
        city: 'Chicago',
        country: 'USA',
        category: VendorCategory.EQUIPMENT_MANUFACTURER,
        rating: 4.8,
        contractStartDate: new Date('2022-01-01'),
        contractEndDate: new Date('2027-12-31'),
        paymentTerms: 'Net 45',
        isActive: true,
        createdAt: new Date('2022-01-01'),
        updatedAt: new Date('2024-09-01')
      },
      {
        id: 'VEN-RCH-002',
        tenantId: 'tenant-4',
        name: 'Varian Medical Systems',
        contactPerson: 'Dr. Susan Park',
        email: 'susan.park@varian.com',
        phone: '(650) 555-0200',
        address: '3100 Hansen Way',
        city: 'Palo Alto',
        country: 'USA',
        category: VendorCategory.EQUIPMENT_MANUFACTURER,
        rating: 4.9,
        contractStartDate: new Date('2022-06-01'),
        contractEndDate: new Date('2027-05-31'),
        paymentTerms: 'Net 60',
        isActive: true,
        createdAt: new Date('2022-06-01'),
        updatedAt: new Date('2024-10-15')
      },
      {
        id: 'VEN-RCH-003',
        tenantId: 'tenant-4',
        name: 'Intuitive Surgical',
        contactPerson: 'Michael Chang',
        email: 'mchang@intusurg.com',
        phone: '(408) 555-0300',
        address: '1020 Kifer Road',
        city: 'Sunnyvale',
        country: 'USA',
        category: VendorCategory.EQUIPMENT_MANUFACTURER,
        rating: 4.8,
        contractStartDate: new Date('2023-04-01'),
        contractEndDate: new Date('2028-03-31'),
        paymentTerms: 'Net 45',
        isActive: true,
        createdAt: new Date('2023-04-01'),
        updatedAt: new Date('2024-11-20')
      },
      {
        id: 'VEN-RCH-004',
        tenantId: 'tenant-4',
        name: 'Midwest Medical Supplies',
        contactPerson: 'Karen Miller',
        email: 'kmiller@midwestmedical.com',
        phone: '(312) 555-0400',
        address: '2500 Industrial Blvd',
        city: 'Chicago',
        country: 'USA',
        category: VendorCategory.CONSUMABLES_SUPPLIER,
        rating: 4.4,
        paymentTerms: 'Net 30',
        isActive: true,
        createdAt: new Date('2022-09-01'),
        updatedAt: new Date('2024-12-01')
      },
      {
        id: 'VEN-RCH-005',
        tenantId: 'tenant-4',
        name: 'Roche Diagnostics Midwest',
        contactPerson: 'David Kim',
        email: 'david.kim@roche.com',
        phone: '(317) 555-0500',
        address: '9115 Hague Road',
        city: 'Indianapolis',
        country: 'USA',
        category: VendorCategory.EQUIPMENT_MANUFACTURER,
        rating: 4.6,
        contractStartDate: new Date('2023-10-01'),
        contractEndDate: new Date('2028-09-30'),
        paymentTerms: 'Net 45',
        isActive: true,
        createdAt: new Date('2023-10-01'),
        updatedAt: new Date('2024-10-01')
      }
    ];
  }
  
  private generateAlertData(): Alert[] {
    return [
      {
        id: 'ALT001',
        tenantId: 'tenant-1',
        type: AlertType.LOW_STOCK,
        severity: AlertSeverity.HIGH,
        title: 'Low Stock Alert',
        message: 'Disposable Syringes 10ml stock is below reorder level (85 units)',
        relatedItemId: 'INV002',
        relatedItemType: 'inventory',
        isRead: false,
        isAcknowledged: false,
        createdAt: new Date('2025-01-20')
      },
      {
        id: 'ALT002',
        tenantId: 'tenant-1',
        type: AlertType.LOW_STOCK,
        severity: AlertSeverity.CRITICAL,
        title: 'Out of Stock',
        message: 'Nitrile Gloves Medium is out of stock! Immediate reorder required.',
        relatedItemId: 'INV005',
        relatedItemType: 'inventory',
        isRead: false,
        isAcknowledged: false,
        createdAt: new Date('2025-01-15')
      },
      {
        id: 'ALT003',
        tenantId: 'tenant-1',
        type: AlertType.MAINTENANCE_OVERDUE,
        severity: AlertSeverity.HIGH,
        title: 'Maintenance Overdue',
        message: 'ECG Machine (MED-2024-008) maintenance is overdue by 81 days',
        relatedItemId: 'EQ008',
        relatedItemType: 'equipment',
        isRead: true,
        isAcknowledged: false,
        createdAt: new Date('2024-11-01')
      },
      {
        id: 'ALT004',
        tenantId: 'tenant-1',
        type: AlertType.MAINTENANCE_DUE,
        severity: AlertSeverity.MEDIUM,
        title: 'Upcoming Maintenance',
        message: 'Defibrillator (MED-2024-004) maintenance due on January 1, 2025',
        relatedItemId: 'EQ004',
        relatedItemType: 'equipment',
        isRead: true,
        isAcknowledged: true,
        createdAt: new Date('2024-12-15')
      },
      {
        id: 'ALT005',
        tenantId: 'tenant-1',
        type: AlertType.WARRANTY_EXPIRING,
        severity: AlertSeverity.MEDIUM,
        title: 'Warranty Expiring',
        message: 'Patient Monitor ICU (MED-2024-002) warranty expires on August 20, 2025',
        relatedItemId: 'EQ002',
        relatedItemType: 'equipment',
        isRead: false,
        isAcknowledged: false,
        createdAt: new Date('2025-01-18')
      },
      {
        id: 'ALT006',
        tenantId: 'tenant-1',
        type: AlertType.EXPIRY_WARNING,
        severity: AlertSeverity.MEDIUM,
        title: 'Reagent Expiring Soon',
        message: 'CBC Reagent Kit expires on April 30, 2025 (12 units in stock)',
        relatedItemId: 'INV004',
        relatedItemType: 'inventory',
        isRead: false,
        isAcknowledged: false,
        createdAt: new Date('2025-01-19')
      },
      // ============ Sunrise Medical Center (tenant-2) Alerts ============
      {
        id: 'ALT-SMC-001',
        tenantId: 'tenant-2',
        type: AlertType.LOW_STOCK,
        severity: AlertSeverity.HIGH,
        title: 'Low Stock Alert',
        message: 'Dialysis Tubing Set stock is below reorder level (18 units)',
        relatedItemId: 'INV-SMC-002',
        relatedItemType: 'inventory',
        isRead: false,
        isAcknowledged: false,
        createdAt: new Date('2025-01-18')
      },
      {
        id: 'ALT-SMC-002',
        tenantId: 'tenant-2',
        type: AlertType.LOW_STOCK,
        severity: AlertSeverity.CRITICAL,
        title: 'Out of Stock',
        message: 'Mammography Film is out of stock! Women\'s imaging services may be impacted.',
        relatedItemId: 'INV-SMC-004',
        relatedItemType: 'inventory',
        isRead: false,
        isAcknowledged: false,
        createdAt: new Date('2025-01-15')
      },
      {
        id: 'ALT-SMC-003',
        tenantId: 'tenant-2',
        type: AlertType.EQUIPMENT_FAILURE,
        severity: AlertSeverity.HIGH,
        title: 'Equipment Under Maintenance',
        message: 'Dialysis Machine (SMC-2024-004) is under maintenance. Expected completion: 2 days.',
        relatedItemId: 'EQ-SMC-004',
        relatedItemType: 'equipment',
        isRead: true,
        isAcknowledged: true,
        createdAt: new Date('2025-01-20')
      },
      {
        id: 'ALT-SMC-004',
        tenantId: 'tenant-2',
        type: AlertType.MAINTENANCE_DUE,
        severity: AlertSeverity.MEDIUM,
        title: 'Upcoming Maintenance',
        message: 'Cardiac Cath Lab (SMC-2024-003) calibration due on January 15, 2025',
        relatedItemId: 'EQ-SMC-003',
        relatedItemType: 'equipment',
        isRead: false,
        isAcknowledged: false,
        createdAt: new Date('2025-01-10')
      },
      // ============ Riverside Community Hospital (tenant-4) Alerts ============
      {
        id: 'ALT-RCH-001',
        tenantId: 'tenant-4',
        type: AlertType.EQUIPMENT_FAILURE,
        severity: AlertSeverity.CRITICAL,
        title: 'Critical Equipment Failure',
        message: 'PET/CT Scanner (RCH-2024-005) is non-functional. Nuclear medicine studies redirected.',
        relatedItemId: 'EQ-RCH-005',
        relatedItemType: 'equipment',
        isRead: true,
        isAcknowledged: true,
        createdAt: new Date('2024-10-01')
      },
      {
        id: 'ALT-RCH-002',
        tenantId: 'tenant-4',
        type: AlertType.LOW_STOCK,
        severity: AlertSeverity.HIGH,
        title: 'Low Stock Alert',
        message: 'Da Vinci Instrument Tip Covers below reorder level (6 units). Surgical schedule may be affected.',
        relatedItemId: 'INV-RCH-003',
        relatedItemType: 'inventory',
        isRead: false,
        isAcknowledged: false,
        createdAt: new Date('2025-01-20')
      },
      {
        id: 'ALT-RCH-003',
        tenantId: 'tenant-4',
        type: AlertType.LOW_STOCK,
        severity: AlertSeverity.CRITICAL,
        title: 'Out of Stock',
        message: 'PET Radiotracer (FDG) is out of stock. Note: PET scanner currently non-operational.',
        relatedItemId: 'INV-RCH-007',
        relatedItemType: 'inventory',
        isRead: true,
        isAcknowledged: true,
        createdAt: new Date('2025-01-25')
      },
      {
        id: 'ALT-RCH-004',
        tenantId: 'tenant-4',
        type: AlertType.WARRANTY_EXPIRING,
        severity: AlertSeverity.MEDIUM,
        title: 'Warranty Expiring',
        message: 'ECMO System (RCH-2024-004) warranty expires on February 1, 2027',
        relatedItemId: 'EQ-RCH-004',
        relatedItemType: 'equipment',
        isRead: false,
        isAcknowledged: false,
        createdAt: new Date('2025-01-22')
      },
      {
        id: 'ALT-RCH-005',
        tenantId: 'tenant-4',
        type: AlertType.MAINTENANCE_OVERDUE,
        severity: AlertSeverity.HIGH,
        title: 'Maintenance Overdue',
        message: 'PET/CT Scanner (RCH-2024-005) maintenance is overdue. Equipment currently non-functional.',
        relatedItemId: 'EQ-RCH-005',
        relatedItemType: 'equipment',
        isRead: true,
        isAcknowledged: false,
        createdAt: new Date('2024-10-15')
      },
      {
        id: 'ALT-RCH-006',
        tenantId: 'tenant-4',
        type: AlertType.EXPIRY_WARNING,
        severity: AlertSeverity.MEDIUM,
        title: 'Reagent Expiring Soon',
        message: 'Comprehensive Metabolic Panel Reagent expires on June 30, 2025 (28 kits in stock)',
        relatedItemId: 'INV-RCH-004',
        relatedItemType: 'inventory',
        isRead: false,
        isAcknowledged: false,
        createdAt: new Date('2025-01-15')
      }
    ];
  }
  
  // Methods to update data
  markAlertAsRead(alertId: string): void {
    this._alerts.update(alerts => 
      alerts.map(alert => 
        alert.id === alertId ? { ...alert, isRead: true } : alert
      )
    );
  }
  
  acknowledgeAlert(alertId: string): void {
    this._alerts.update(alerts =>
      alerts.map(alert =>
        alert.id === alertId ? { ...alert, isAcknowledged: true } : alert
      )
    );
  }
  
  getEquipmentById(id: string): Equipment | undefined {
    return this._equipment().find(e => e.id === id);
  }
  
  getInventoryById(id: string): InventoryItem | undefined {
    return this._inventory().find(i => i.id === id);
  }
  
  getVendorById(id: string): Vendor | undefined {
    return this._vendors().find(v => v.id === id);
  }
  
  getAuditLogById(id: string): AuditLog | undefined {
    return this._auditLogs().find(a => a.id === id);
  }

  // Tenant filtering methods
  // These methods filter data by tenant ID for multi-tenancy support

  getEquipmentByTenant(tenantId: string): Equipment[] {
    return this._equipment().filter(e => e.tenantId === tenantId);
  }

  getInventoryByTenant(tenantId: string): InventoryItem[] {
    return this._inventory().filter(i => i.tenantId === tenantId);
  }

  getVendorsByTenant(tenantId: string): Vendor[] {
    return this._vendors().filter(v => v.tenantId === tenantId);
  }

  getMaintenanceRecordsByTenant(tenantId: string): MaintenanceRecord[] {
    return this._maintenanceRecords().filter(m => m.tenantId === tenantId);
  }

  getWorkOrdersByTenant(tenantId: string): WorkOrder[] {
    return this._workOrders().filter(w => w.tenantId === tenantId);
  }

  getAlertsByTenant(tenantId: string): Alert[] {
    return this._alerts().filter(a => a.tenantId === tenantId);
  }

  getAuditLogsByTenant(tenantId: string): AuditLog[] {
    return this._auditLogs();
  }

  getDashboardStatsByTenant(tenantId: string): DashboardStats {
    // Temporarily set tenant to get filtered stats
    const currentTenant = this.currentTenantId();
    this.currentTenantId.set(tenantId);
    const stats = this.dashboardStats();
    this.currentTenantId.set(currentTenant);
    return stats;
  }
  
  private generateAuditLogData(): AuditLog[] {
    const users = [
      { id: 'USR001', name: 'System Administrator', role: 'Admin' },
      { id: 'USR002', name: 'Dr. Sarah Wilson', role: 'Manager' },
      { id: 'USR003', name: 'Michael Chen', role: 'Technician' },
      { id: 'USR004', name: 'Emily Johnson', role: 'Manager' },
      { id: 'USR005', name: 'Robert Martinez', role: 'Technician' },
      { id: 'USR006', name: 'Jennifer Lee', role: 'Viewer' }
    ];
    
    const ipAddresses = ['192.168.1.100', '192.168.1.105', '192.168.1.110', '10.0.0.50', '10.0.0.55'];
    
    return [
      {
        id: 'AUD001',
        timestamp: new Date('2025-01-22T09:15:00'),
        userId: users[0].id,
        userName: users[0].name,
        userRole: users[0].role,
        action: AuditAction.LOGIN,
        resourceType: AuditResourceType.SYSTEM,
        resourceId: 'SYS001',
        resourceName: 'GoEMR Inventory System',
        description: 'User logged into the system',
        ipAddress: ipAddresses[0],
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0',
        sessionId: 'SES-2025-001',
        status: 'Success'
      },
      {
        id: 'AUD002',
        timestamp: new Date('2025-01-22T09:20:00'),
        userId: users[0].id,
        userName: users[0].name,
        userRole: users[0].role,
        action: AuditAction.UPDATE,
        resourceType: AuditResourceType.EQUIPMENT,
        resourceId: 'MED-2024-001',
        resourceName: 'Portable X-Ray System',
        description: 'Updated equipment maintenance schedule',
        changes: [
          { field: 'nextMaintenanceDate', fieldLabel: 'Next Maintenance Date', oldValue: '2025-02-15', newValue: '2025-02-01' },
          { field: 'notes', fieldLabel: 'Notes', oldValue: '', newValue: 'Prioritized due to high usage' }
        ],
        ipAddress: ipAddresses[0],
        sessionId: 'SES-2025-001',
        status: 'Success'
      },
      {
        id: 'AUD003',
        timestamp: new Date('2025-01-22T10:05:00'),
        userId: users[2].id,
        userName: users[2].name,
        userRole: users[2].role,
        action: AuditAction.LOGIN,
        resourceType: AuditResourceType.SYSTEM,
        resourceId: 'SYS001',
        resourceName: 'GoEMR Inventory System',
        description: 'User logged into the system',
        ipAddress: ipAddresses[1],
        sessionId: 'SES-2025-002',
        status: 'Success'
      },
      {
        id: 'AUD004',
        timestamp: new Date('2025-01-22T10:15:00'),
        userId: users[2].id,
        userName: users[2].name,
        userRole: users[2].role,
        action: AuditAction.COMPLETE,
        resourceType: AuditResourceType.MAINTENANCE,
        resourceId: 'MNT-2025-001',
        resourceName: 'Ventilator Preventive Maintenance',
        description: 'Completed scheduled maintenance task',
        changes: [
          { field: 'status', fieldLabel: 'Status', oldValue: 'In Progress', newValue: 'Completed' },
          { field: 'completedDate', fieldLabel: 'Completed Date', oldValue: null, newValue: '2025-01-22' }
        ],
        ipAddress: ipAddresses[1],
        sessionId: 'SES-2025-002',
        status: 'Success'
      },
      {
        id: 'AUD005',
        timestamp: new Date('2025-01-22T10:30:00'),
        userId: users[1].id,
        userName: users[1].name,
        userRole: users[1].role,
        action: AuditAction.CREATE,
        resourceType: AuditResourceType.INVENTORY,
        resourceId: 'INV-2025-009',
        resourceName: 'Surgical Masks N95',
        description: 'Added new inventory item',
        ipAddress: ipAddresses[2],
        sessionId: 'SES-2025-003',
        status: 'Success'
      },
      {
        id: 'AUD006',
        timestamp: new Date('2025-01-22T11:00:00'),
        userId: users[3].id,
        userName: users[3].name,
        userRole: users[3].role,
        action: AuditAction.EXPORT,
        resourceType: AuditResourceType.REPORT,
        resourceId: 'RPT-2025-001',
        resourceName: 'Monthly Equipment Status Report',
        description: 'Exported report to PDF format',
        metadata: { format: 'PDF', pages: 12, fileSize: '2.4 MB' },
        ipAddress: ipAddresses[3],
        sessionId: 'SES-2025-004',
        status: 'Success'
      },
      {
        id: 'AUD007',
        timestamp: new Date('2025-01-22T11:30:00'),
        userId: users[0].id,
        userName: users[0].name,
        userRole: users[0].role,
        action: AuditAction.UPDATE,
        resourceType: AuditResourceType.VENDOR,
        resourceId: 'VND-001',
        resourceName: 'MedEquip Solutions Inc.',
        description: 'Updated vendor contact information',
        changes: [
          { field: 'contactEmail', fieldLabel: 'Contact Email', oldValue: 'old@medequip.com', newValue: 'support@medequip.com' },
          { field: 'phone', fieldLabel: 'Phone', oldValue: '+1-555-0100', newValue: '+1-555-0150' }
        ],
        ipAddress: ipAddresses[0],
        sessionId: 'SES-2025-001',
        status: 'Success'
      },
      {
        id: 'AUD008',
        timestamp: new Date('2025-01-22T12:00:00'),
        userId: users[4].id,
        userName: users[4].name,
        userRole: users[4].role,
        action: AuditAction.SCHEDULE,
        resourceType: AuditResourceType.MAINTENANCE,
        resourceId: 'MNT-2025-005',
        resourceName: 'MRI Scanner Calibration',
        description: 'Scheduled calibration maintenance',
        ipAddress: ipAddresses[4],
        sessionId: 'SES-2025-005',
        status: 'Success'
      },
      {
        id: 'AUD009',
        timestamp: new Date('2025-01-22T13:15:00'),
        userId: users[1].id,
        userName: users[1].name,
        userRole: users[1].role,
        action: AuditAction.APPROVE,
        resourceType: AuditResourceType.COMPLIANCE,
        resourceId: 'CMP-2025-001',
        resourceName: 'HIPAA Compliance Audit',
        description: 'Approved compliance documentation',
        ipAddress: ipAddresses[2],
        sessionId: 'SES-2025-003',
        status: 'Success'
      },
      {
        id: 'AUD010',
        timestamp: new Date('2025-01-22T14:00:00'),
        userId: users[5].id,
        userName: users[5].name,
        userRole: users[5].role,
        action: AuditAction.READ,
        resourceType: AuditResourceType.EQUIPMENT,
        resourceId: 'MED-2024-003',
        resourceName: 'Patient Monitor ICU',
        description: 'Viewed equipment details',
        ipAddress: ipAddresses[3],
        sessionId: 'SES-2025-006',
        status: 'Success'
      },
      {
        id: 'AUD011',
        timestamp: new Date('2025-01-21T16:30:00'),
        userId: users[0].id,
        userName: users[0].name,
        userRole: users[0].role,
        action: AuditAction.DELETE,
        resourceType: AuditResourceType.ALERT,
        resourceId: 'ALT-2024-050',
        resourceName: 'Resolved Low Stock Alert',
        description: 'Dismissed resolved alert notification',
        ipAddress: ipAddresses[0],
        sessionId: 'SES-2025-001',
        status: 'Success'
      },
      {
        id: 'AUD012',
        timestamp: new Date('2025-01-21T15:00:00'),
        userId: users[2].id,
        userName: users[2].name,
        userRole: users[2].role,
        action: AuditAction.UPDATE,
        resourceType: AuditResourceType.EQUIPMENT,
        resourceId: 'MED-2024-005',
        resourceName: 'Defibrillator AED',
        description: 'Updated equipment status',
        changes: [
          { field: 'status', fieldLabel: 'Status', oldValue: 'Under Maintenance', newValue: 'In Service' },
          { field: 'condition', fieldLabel: 'Condition', oldValue: 'Fair', newValue: 'Good' }
        ],
        ipAddress: ipAddresses[1],
        sessionId: 'SES-2025-002',
        status: 'Success'
      },
      {
        id: 'AUD013',
        timestamp: new Date('2025-01-21T11:45:00'),
        userId: users[3].id,
        userName: users[3].name,
        userRole: users[3].role,
        action: AuditAction.TRANSFER,
        resourceType: AuditResourceType.EQUIPMENT,
        resourceId: 'MED-2024-007',
        resourceName: 'Ultrasound System',
        description: 'Transferred equipment to new location',
        changes: [
          { field: 'location.building', fieldLabel: 'Building', oldValue: 'Main Building', newValue: 'East Wing' },
          { field: 'location.room', fieldLabel: 'Room', oldValue: 'Room 201', newValue: 'Room 405' },
          { field: 'department', fieldLabel: 'Department', oldValue: 'Radiology', newValue: 'Obstetrics' }
        ],
        ipAddress: ipAddresses[3],
        sessionId: 'SES-2025-004',
        status: 'Success'
      },
      {
        id: 'AUD014',
        timestamp: new Date('2025-01-21T09:00:00'),
        userId: users[1].id,
        userName: users[1].name,
        userRole: users[1].role,
        action: AuditAction.CREATE,
        resourceType: AuditResourceType.VENDOR,
        resourceId: 'VND-010',
        resourceName: 'BioTech Instruments Ltd.',
        description: 'Added new vendor to the system',
        ipAddress: ipAddresses[2],
        sessionId: 'SES-2025-003',
        status: 'Success'
      },
      {
        id: 'AUD015',
        timestamp: new Date('2025-01-20T14:30:00'),
        userId: users[0].id,
        userName: users[0].name,
        userRole: users[0].role,
        action: AuditAction.IMPORT,
        resourceType: AuditResourceType.INVENTORY,
        resourceId: 'BATCH-2025-001',
        resourceName: 'Inventory Batch Import',
        description: 'Bulk imported 25 inventory items from CSV',
        metadata: { itemCount: 25, format: 'CSV', fileSize: '45 KB' },
        ipAddress: ipAddresses[0],
        sessionId: 'SES-2025-001',
        status: 'Success'
      },
      {
        id: 'AUD016',
        timestamp: new Date('2025-01-20T10:20:00'),
        userId: users[4].id,
        userName: users[4].name,
        userRole: users[4].role,
        action: AuditAction.UPDATE,
        resourceType: AuditResourceType.MAINTENANCE,
        resourceId: 'MNT-2025-002',
        resourceName: 'CT Scanner Annual Service',
        description: 'Failed to update maintenance record - validation error',
        ipAddress: ipAddresses[4],
        sessionId: 'SES-2025-005',
        status: 'Failed',
        metadata: { errorCode: 'VAL_001', errorMessage: 'Invalid date format' }
      },
      {
        id: 'AUD017',
        timestamp: new Date('2025-01-19T16:00:00'),
        userId: users[2].id,
        userName: users[2].name,
        userRole: users[2].role,
        action: AuditAction.ASSIGN,
        resourceType: AuditResourceType.MAINTENANCE,
        resourceId: 'MNT-2025-003',
        resourceName: 'Infusion Pump Inspection',
        description: 'Assigned maintenance task to technician',
        changes: [
          { field: 'assignedTo', fieldLabel: 'Assigned To', oldValue: null, newValue: 'Robert Martinez' }
        ],
        ipAddress: ipAddresses[1],
        sessionId: 'SES-2025-002',
        status: 'Success'
      },
      {
        id: 'AUD018',
        timestamp: new Date('2025-01-19T11:30:00'),
        userId: users[0].id,
        userName: users[0].name,
        userRole: users[0].role,
        action: AuditAction.ARCHIVE,
        resourceType: AuditResourceType.EQUIPMENT,
        resourceId: 'MED-2023-015',
        resourceName: 'Old ECG Machine',
        description: 'Archived decommissioned equipment record',
        changes: [
          { field: 'status', fieldLabel: 'Status', oldValue: 'Decommissioned', newValue: 'Disposed' },
          { field: 'archived', fieldLabel: 'Archived', oldValue: false, newValue: true }
        ],
        ipAddress: ipAddresses[0],
        sessionId: 'SES-2025-001',
        status: 'Success'
      },
      {
        id: 'AUD019',
        timestamp: new Date('2025-01-18T09:45:00'),
        userId: users[1].id,
        userName: users[1].name,
        userRole: users[1].role,
        action: AuditAction.REJECT,
        resourceType: AuditResourceType.COMPLIANCE,
        resourceId: 'CMP-2025-002',
        resourceName: 'Equipment Disposal Request',
        description: 'Rejected disposal request - incomplete documentation',
        metadata: { reason: 'Missing hazardous materials certification' },
        ipAddress: ipAddresses[2],
        sessionId: 'SES-2025-003',
        status: 'Success'
      },
      {
        id: 'AUD020',
        timestamp: new Date('2025-01-18T08:00:00'),
        userId: users[0].id,
        userName: users[0].name,
        userRole: users[0].role,
        action: AuditAction.LOGOUT,
        resourceType: AuditResourceType.SYSTEM,
        resourceId: 'SYS001',
        resourceName: 'GoEMR Inventory System',
        description: 'User logged out of the system',
        ipAddress: ipAddresses[0],
        sessionId: 'SES-2024-999',
        status: 'Success'
      }
    ];
  }
}
